import { test, expect } from '@playwright/test';
test('renders the 3D board, flags/reveals, restarts, switches difficulty, and validates custom dimensions', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto('/');
  await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  await expect(page.getByText('三维渲染暂不可用')).toBeHidden();
  const canvas = page.locator('canvas');
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true);
  const mode = (await page.locator('.mode-toggle').boundingBox())!, field = (await page.locator('.field').boundingBox())!;
  const nav = (await page.locator('.menu-bar').boundingBox())!;
  expect(mode.y).toBeGreaterThanOrEqual(nav.y); expect(mode.y + mode.height).toBeLessThanOrEqual(nav.y + nav.height);
  expect(mode.height).toBeLessThanOrEqual(28);
  await expect(page.locator('.bottom-panel, .status-bar')).toHaveCount(0);
  await expect(page.locator('header')).toHaveCount(0);
  await canvas.focus(); await page.keyboard.press('f');
  await expect(page.getByRole('status', { name: '剩余地雷 9', exact: true })).toBeVisible();
  await page.keyboard.press('f'); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Enter');
  await expect(page.locator('.field')).toHaveAttribute('data-status', 'playing');
  await page.waitForTimeout(500); // Capture the 220 ms reveal wave after its last tile settles.
  await page.screenshot({ path: '../minesweeper-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '重新开始', exact: true }).click();
  await expect(page.getByRole('status', { name: '剩余地雷 10', exact: true })).toBeVisible();
  await page.getByLabel('难度', { exact: true }).selectOption('expert');
  await expect(page.getByRole('status', { name: '剩余地雷 99', exact: true })).toBeVisible();
  await expect(canvas).toHaveAttribute('aria-label', /30 列, 16 行/);
  await page.getByLabel('难度', { exact: true }).selectOption('custom');
  await page.getByLabel('宽度', { exact: true }).fill('12'); await page.getByLabel('高度', { exact: true }).fill('8'); await page.getByLabel('地雷数量', { exact: true }).fill('15');
  await page.getByRole('button', { name: '开始游戏', exact: true }).click();
  await expect(canvas).toHaveAttribute('aria-label', /12 列, 8 行/);
  await expect(page.getByRole('status', { name: '剩余地雷 15', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByLabel('画质', { exact: true }).selectOption('low');
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.reload(); await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await expect(page.getByLabel('画质', { exact: true })).toHaveValue('low');
  expect(errors).toEqual([]);
});
test('touch layout stays within the viewport and supports long press without accidental reveal', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1, locale: 'zh-CN' });
  const page = await context.newPage(); await page.goto('/');
  await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  await expect(page.getByText('三维渲染暂不可用')).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '翻开模式', exact: true }).click();
  const canvas = page.locator('canvas'), rect = (await canvas.boundingBox())!;
  await page.touchscreen.tap(rect.x + rect.width / 2, rect.y + rect.height / 2);
  await expect(page.getByRole('status', { name: '剩余地雷 9', exact: true })).toBeVisible();
  await expect(page.locator('.field')).toHaveAttribute('data-status', 'ready');
  await page.getByRole('button', { name: '插旗模式', exact: true }).click();
  const session = await context.newCDPSession(page);
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: rect.x + rect.width / 2, y: rect.y + rect.height / 2, id: 1 }] });
  await page.waitForTimeout(600);
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(page.getByRole('status', { name: '剩余地雷 10', exact: true })).toBeVisible();
  await page.touchscreen.tap(rect.x + rect.width / 2, rect.y + rect.height / 2);
  await expect(page.locator('.field')).toHaveAttribute('data-status', 'playing');
  await page.screenshot({ path: '../minesweeper-mobile.png', fullPage: true });
  const cabinet = (await page.locator('.cabinet').boundingBox())!;
  expect(cabinet.height).toBe(844); expect(cabinet.width).toBe(390);
  await page.getByLabel('难度', { exact: true }).selectOption('expert');
  await expect(page.locator('canvas')).toHaveAttribute('aria-label', /16 列, 30 行/);
  await page.getByLabel('难度', { exact: true }).selectOption('custom');
  await page.getByLabel('宽度', { exact: true }).fill('20'); await page.getByLabel('高度', { exact: true }).fill('10');
  await page.getByLabel('地雷数量', { exact: true }).fill('30');
  await page.getByRole('button', { name: '开始游戏', exact: true }).click();
  await expect(page.locator('canvas')).toHaveAttribute('aria-label', /10 列, 20 行/);
  await page.getByLabel('难度', { exact: true }).selectOption('custom');
  await page.getByLabel('宽度', { exact: true }).fill('40'); await page.getByLabel('高度', { exact: true }).fill('5');
  await page.getByRole('button', { name: '开始游戏', exact: true }).click();
  await expect(page.locator('canvas')).toHaveAttribute('aria-label', /5 列, 40 行/);
  await context.close();
});
test('phone cells stay square across presets, custom dimensions, zoom, and resize', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'zh-CN' });
  const page = await context.newPage();
  await page.addInitScript(() => localStorage.setItem('real-mines-settings', JSON.stringify({ quality: 'low', reducedMotion: true })));
  await page.goto('/');
  await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  const squareCells = async (width: number, height: number) => {
    const field = (await page.locator('.field').boundingBox())!, x = field.x + field.width / 2 + .3, y = field.y + field.height / 2 + .3;
    const at = async (dx: number, dy: number) => {
      await page.mouse.move(x + dx, y + dy);
      await page.waitForTimeout(20);
      return page.locator('#cell-description').textContent();
    };
    const center = await at(0, 0), limit = Math.min(field.width / width, field.height / height) * 2;
    const edge = async (dx: number, dy: number) => {
      let low = 0, high = limit;
      for (let i = 0; i < 7; i++) {
        const distance = (low + high) / 2;
        if (await at(dx * distance, dy * distance) === center) low = distance; else high = distance;
      }
      return (low + high) / 2;
    };
    // Measure real picking boundaries in screen pixels, rather than trusting CSS or model dimensions.
    const pitchX = await edge(-1, 0) + await edge(1, 0), pitchY = await edge(0, -1) + await edge(0, 1);
    expect(pitchX).toBeGreaterThan(5); expect(Math.abs(pitchX - pitchY)).toBeLessThan(1);
  };
  await squareCells(9, 9);
  const field = (await page.locator('.field').boundingBox())!;
  await page.mouse.click(field.x + field.width / 2, field.y + field.height / 2);
  await page.waitForTimeout(450); await squareCells(9, 9);
  await page.mouse.wheel(0, -180); await page.waitForTimeout(100); await squareCells(9, 9);
  await page.getByLabel('难度', { exact: true }).selectOption('expert'); await squareCells(16, 30);
  await page.setViewportSize({ width: 430, height: 900 }); await page.waitForTimeout(100); await squareCells(16, 30);
  await page.getByLabel('难度', { exact: true }).selectOption('custom');
  await page.getByLabel('宽度', { exact: true }).fill('40'); await page.getByLabel('高度', { exact: true }).fill('5');
  await page.getByRole('button', { name: '开始游戏', exact: true }).click(); await squareCells(5, 40);
  await context.close();
});
test('production build reloads and plays offline with all render assets bundled', async ({ browser }) => {
  const context = await browser.newContext({ locale: 'en-US' });
  const page = await context.newPage(), external: string[] = [], errors: string[] = [];
  page.on('request', r => { const url = new URL(r.url()); if (url.protocol !== 'data:' && url.origin !== 'http://127.0.0.1:5174') external.push(r.url()); });
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:5174/');
  await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  await page.evaluate(async () => { await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) await new Promise<void>(resolve => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), { once: true })); });
  await context.setOffline(true); await page.reload();
  await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  await expect(page.getByText('3D rendering unavailable')).toBeHidden();
  await page.locator('canvas').focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.field')).toHaveAttribute('data-status', 'playing');
  expect(external).toEqual([]); expect(errors).toEqual([]);
  await context.close();
});
test('follows system language and persists an explicit override without restarting the game', async ({ browser }) => {
  const context = await browser.newContext({ locale: 'en-US', viewport: { width: 900, height: 750 } });
  const page = await context.newPage(); await page.goto('/');
  await expect(page.getByText('Preparing your field…')).toBeHidden({ timeout: 45000 });
  await expect(page.getByRole('button', { name: 'New game', exact: true })).toBeVisible();
  await page.locator('canvas').focus(); await page.keyboard.press('f');
  await expect(page.getByRole('status', { name: 'Mines remaining 9', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByLabel('Language', { exact: true }).selectOption('zh');
  await expect(page.getByRole('heading', { name: '设置', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.getByRole('status', { name: '剩余地雷 9', exact: true })).toBeVisible();
  await page.reload(); await expect(page.locator('.field')).toHaveAttribute('aria-busy', 'false', { timeout: 45000 });
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await expect(page.getByLabel('语言', { exact: true })).toHaveValue('zh');
  await page.getByLabel('语言', { exact: true }).selectOption('auto');
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible();
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await context.close();
});
